### ISSUE TITLE
时间同步处的疑惑

### ISSUE THREAD

**Issue by nixsui** [XuankeShi/CurlingHunter#1]
您好，我看了您的那篇论文，到时间同步那里有些不理解
![image](https://github.com/XuankeShi/CurlingHunter/assets/42858061/1004ffb6-5703-48e8-bec4-9a5c48557d2a)
这段的描述是使用其他相机的轨迹去插值处当前的轨迹信息。但是公式上看是时间维度的。
![image](https://github.com/XuankeShi/CurlingHunter/assets/42858061/67a96e85-8e1b-4581-9bd1-f9d8a0caa03e)
然后这张图上我没有理解是怎么做的插值，因为这个图如果下表代表时间，那么就是a, b, c时刻每个0号相机和1号相机的位置关系，但是在b时刻1号相机的位置已经可以观测出来了，为什么还要插值呢？
望回复。

**Comment by XuankeShi** [comment]
你好, 非常高兴你对其中的细节感兴趣. 
具体实现是这样子的.  因为各个相机捕获到的图像的时间戳并不是严格对齐的, 我们对此做了一个优化. 利用每个相机的前一帧时刻的位置坐标 和 当前时刻的位置坐标, 来插值出所有相机中第一个返回接收到的相机坐标位置. 使得各个相机接受到的冰壶的位置信息可以保持时间上同步一致性. 当然, 这种线性插值只有在单目相机追踪(SOT)没有失效的前提下进行的, 不过也会提高整个系统的精度和稳定性.

**Comment by XuankeShi** [comment]
> 您好，我看了您的那篇论文，到时间同步那里有些不理解 ![image](https://user-images.githubusercontent.com/42858061/257691120-1004ffb6-5703-48e8-bec4-9a5c48557d2a.png) 这段的描述是使用其他相机的轨迹去插值处当前的轨迹信息。但是公式上看是时间维度的。 ![image](https://user-images.githubusercontent.com/42858061/257691257-67a96e85-8e1b-4581-9bd1-f9d8a0caa03e.png) 然后这张图上我没有理解是怎么做的插值，因为这个图如果下表代表时间，那么就是a, b, c时刻每个0号相机和1号相机的位置关系，但是在b时刻1号相机的位置已经可以观测出来了，为什么还要插值呢？ 望回复。

你好, 非常高兴你对其中的细节感兴趣.
具体实现是这样子的. **因为各个相机同一批次捕获到的图像信息的时间戳并不是严格对齐的, 我们对此做了一个优化**. 利用每个相机的**前一帧时刻**的所有冰壶的位置坐标 和 **当前时刻**所有冰壶的位置坐标, 来插值出各个相机在**同一批次**接受图像中的**最早时刻**(第一个返回接收到图像信息的对应相机时刻) 下的冰壶坐标位置(注意各个相机接收到的同一批图像的时间戳并不是完全的对齐, 存在一定的系统误差和随机误差). 使得各个相机接受到的冰壶的位置信息可以**保持时间上同步一致性**(尽量保证得到的信息是在同一时间戳下的冰壶位置信息). 当然, 这种线性插值只有在单目相机追踪(SOT)没有失效的前提下进行的, 不过也会提高整个系统的精度和稳定性

**Comment by XuankeShi** [comment]
> > 您好，我看了您的那篇论文，到时间同步那里有些不理解 ![image](https://user-images.githubusercontent.com/42858061/257691120-1004ffb6-5703-48e8-bec4-9a5c48557d2a.png) 这段的描述是使用其他相机的轨迹去插值处当前的轨迹信息。但是公式上看是时间维度的。 ![image](https://user-images.githubusercontent.com/42858061/257691257-67a96e85-8e1b-4581-9bd1-f9d8a0caa03e.png) 然后这张图上我没有理解是怎么做的插值，因为这个图如果下表代表时间，那么就是a, b, c时刻每个0号相机和1号相机的位置关系，但是在b时刻1号相机的位置已经可以观测出来了，为什么还要插值呢？ 望回复。
> 
> 你好, 非常高兴你对其中的细节感兴趣. 具体实现是这样子的. **因为各个相机同一批次捕获到的图像信息的时间戳并不是严格对齐的, 我们对此做了一个优化**. 利用每个相机的**前一帧时刻**的所有冰壶的位置坐标 和 **当前时刻**所有冰壶的位置坐标, 来插值出各个相机在**同一批次**接受图像中的**最早时刻**(第一个返回接收到图像信息的对应相机时刻) 下的冰壶坐标位置(注意各个相机接收到的同一批图像的时间戳并不是完全的对齐, 存在一定的系统误差和随机误差). 使得各个相机接受到的冰壶的位置信息可以**保持时间上同步一致性**(尽量保证得到的信息是在同一时间戳下的冰壶位置信息). 当然, 这种线性插值只有在单目相机追踪(SOT)没有失效的前提下进行的, 不过也会提高整个系统的精度和稳定性

详细问题可以加我

**Comment by XuankeShi** [comment]
> 您好，我看了您的那篇论文，到时间同步那里有些不理解 ![image](https://user-images.githubusercontent.com/42858061/257691120-1004ffb6-5703-48e8-bec4-9a5c48557d2a.png) 这段的描述是使用其他相机的轨迹去插值处当前的轨迹信息。但是公式上看是时间维度的。 ![image](https://user-images.githubusercontent.com/42858061/257691257-67a96e85-8e1b-4581-9bd1-f9d8a0caa03e.png) 然后这张图上我没有理解是怎么做的插值，因为这个图如果下表代表时间，那么就是a, b, c时刻每个0号相机和1号相机的位置关系，但是在b时刻1号相机的位置已经可以观测出来了，为什么还要插值呢？ 望回复。

wechat: sxk827935948

**Comment by nixsui** [comment]
那我理解这个图里面的a,b,c是不是应该代表不同的相机，而非不同的时间呀。然后0,1代表时间戳。

**Comment by XuankeShi** [comment]
> 那我理解这个图里面的a,b,c是不是应该代表不同的相机，而非不同的时间呀。然后0,1代表时间戳。

是的, 你理解的没问题
